{% set name = "meinheld" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 008c76937ac2117cc69e032dc69cea9f85fc605de9bac1417f447c41c16a56d6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - greenlet >=0.4.5,<0.5
    - python

test:
  imports:
    - meinheld

about:
  home: https://meinheld.org/
  summary: High performance asynchronous Python WSGI Web Server
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/mopemope/meinheld

extra:
  recipe-maintainers:
    - synapticarbors
